//@ts-check
import defaultTheme from 'tailwindcss/defaultTheme.js';
import animatePlugin from 'tailwindcss-animate';

/** @type { Omit<import('tailwindcss').Config, 'content'> } */
export default {
  theme: {
    extend: {
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
        13: '52px',
        14: '56px',
        15: '60px',
        16: '64px',
        17: '68px',
        18: '72px',
        19: '76px',
        20: '80px',
        21: '84px',
        22: '88px',
        23: '92px',
        24: '96px',
        25: '100px',
        26: '104px',
        27: '108px',
        28: '112px',
        29: '116px',
        30: '120px',
        31: '124px',
        32: '128px',
        33: '132px',
        34: '136px',
        35: '140px',
        36: '144px',
        37: '148px',
        38: '152px',
        39: '156px',
        40: '160px',
        41: '164px',
        42: '168px',
        43: '172px',
        44: '176px',
        45: '180px',
        46: '184px',
        47: '188px',
        48: '192px',
        49: '196px',
        50: '200px',
        51: '204px',
        52: '208px',
        53: '212px',
        54: '216px',
        55: '220px',
        56: '224px',
        57: '228px',
        58: '232px',
        59: '236px',
        60: '240px',
        61: '244px',
        62: '248px',
        63: '252px',
        64: '256px',
        65: '260px',
        66: '264px',
        67: '268px',
        68: '272px',
        69: '276px',
        70: '280px',
        71: '284px',
        72: '288px',
        73: '292px',
        74: '296px',
        75: '300px',
        76: '304px',
        77: '308px',
        78: '312px',
        79: '316px',
        80: '320px',
      },
      fontSize: {
        xs: ['12px', '16px'],
        sm: ['14px', '20px'],
        base: ['16px', '24px'],
        lg: ['18px', '28px'],
        xl: ['20px', '32px'],
        '2xl': ['24px', '36px'],
      },
      colors: {
        border: 'hsl(var(--ribbit-border))',
        input: 'hsl(var(--ribbit-input))',
        ring: 'hsl(var(--ribbit-ring))',
        background: 'hsl(var(--ribbit-background))',
        foreground: 'hsl(var(--ribbit-foreground))',
        primary: {
          DEFAULT: 'hsl(var(--ribbit-primary))',
          foreground: 'hsl(var(--ribbit-primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--ribbit-secondary))',
          foreground: 'hsl(var(--ribbit-secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--ribbit-destructive))',
          foreground: 'hsl(var(--ribbit-destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--ribbit-muted))',
          foreground: 'hsl(var(--ribbit-muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--ribbit-accent))',
          foreground: 'hsl(var(--ribbit-accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--ribbit-popover))',
          foreground: 'hsl(var(--ribbit-popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--ribbit-card))',
          foreground: 'hsl(var(--ribbit-card-foreground))',
        },
      },
      borderRadius: {
        lg: `var(--ribbit-radius)`,
        md: `calc(var(--ribbit-radius) - 2px)`,
        sm: 'calc(var(--ribbit-radius) - 4px)',
      },
      fontFamily: {
        sans: ['var(--ribbit-font-sans)', ...defaultTheme.fontFamily.sans],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--ribbit-radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--ribbit-radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [animatePlugin],
};
